name: Event filters
on: 
    push:
        branches:
            - test-branch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Run a script
              run: echo "This workflow runs on push to main branch"